### ISSUE TITLE
Striktnější stardard

### ISSUE THREAD

**Issue by vitkutny** [peckadesign/CodingStandard#10]
Kromě aktuálních pravidel pro celou code base bych přidal i striktnější seznam pravidel, který se bude aplikovat pouze na nově přidané soubory. Aby nový kód byl na úrovni.

- vynutit strict type
- vynutit return/typehinty
- cokoli dalšího na čem se shodnem, že je správně, ale nešlo prozatím nasadit na všechen kód

```sh
#!/bin/bash

FILES=$(git diff --name-only --diff-filter=A master HEAD);
if [ ! -z "$FILES" ]; then
    vendor/bin/phpcs $FILES --standard=vendor/pd/coding-standard/src/PeckaCodingStandard/ruleset-strict.xml --report-file=output-strict.cs
fi
```

cc @peckadesign/programatori , @MilanPala

**Comment by MilanPala** [comment]
Víťo, připrav prosím PR na projektu:
 - Bude se porovnávat oproti nějakému commitu v historii, od kterého je přidaná verze se striktní podporou v PeckaCS. Vzhledem k tomu, že to je na projektu, tak tam je možné uvést konkrétní commit.
 - Oba výstupu můžeš sloučit do jednoho souboru. CI server si s tím poradí.

Připrav v PeckaCS:
 - Sekci se striktními pravidly, třeba jen jedním na jednu classu na soubor
 - Hoď to do PR, ať se na to můžeš odkázat na projektu

Díky

**Comment by MilanPala** [comment]
Tak jo, připraveno v #11. Můžete zkusit nasadit na projektech.
